name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    # Define que o job vai rodar no self-hosted runner
    runs-on: self-hosted

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
